#load "FsCheck.fsx" 
#load "NETStandard.Library.fsx" 
#load "System.ValueTuple.fsx" 
#load "xunit.abstractions.fsx" 
#load "xunit.core.fsx" 
#load "xunit.extensibility.execution.fsx" 
#r "../../../packages/FsCheck.Xunit/lib/netstandard1.6/FsCheck.Xunit.dll" 